/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdint.h>
#include<stdio.h>
#include<led.h>
#include<FreeRTOS.h>
#include<FreeRTOSConfig.h>
#include<task.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vLedTask(void *pvParameters) {
    uint32_t *params = (uint32_t *)pvParameters;
    uint16_t pin = (uint16_t)params[0];
    TickType_t rate = (TickType_t)params[1];

    led_init(pin);

    while (1) {
        led_toggle(pin);
        vTaskDelay(rate);
    }
}
int main(void) {
    static uint32_t greenParams[2]  = { LED_GREEN,  pdMS_TO_TICKS(500) };
    static uint32_t orangeParams[2] = { LED_ORANGE, pdMS_TO_TICKS(300) };
    static uint32_t redParams[2]    = { LED_RED,    pdMS_TO_TICKS(700) };
    static uint32_t blueParams[2]   = { LED_BLUE,   pdMS_TO_TICKS(1000) };

    xTaskCreate(vLedTask, "GreenLED", 128, (void*)greenParams, 1, NULL);
    xTaskCreate(vLedTask, "OrangeLED",128, (void*)orangeParams,1, NULL);
    xTaskCreate(vLedTask, "RedLED",   128, (void*)redParams,   1, NULL);
    xTaskCreate(vLedTask, "BlueLED",  128, (void*)blueParams,  1, NULL);

    vTaskStartScheduler();

    while (1);
}


